language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install unittest2; fi

# command to run tests
script: nosetests