language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

install:
  - pip install -r requirements.txt python-coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install unittest2; fi

script:
  - make pep8
  - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then make flakes; fi
  - make test

after_success:
  - make coveralls

notifications:
  email:
    on_success: change
    on_failure: change